services:
  trading-app:
    build: .
    volumes:
      - .:/app
      - build_volume:/app/build
    environment:
      - LIBGL_ALWAYS_INDIRECT=1
      - QT_QPA_DEBUG=1
    network_mode: "host"
    command: >
      /bin/bash -c "
        cd /app/build &&
        cmake .. -DCMAKE_BUILD_TYPE=Debug &&
        make VERBOSE=1 &&
        gdb -ex run ./MyTradingProject
      "
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    stdin_open: true
    tty: true

networks:
  trading_network:
    driver: bridge

volumes:
  build_volume: